---
# EPEL yum repository.
- name: Install IUS (CentOS) repo.
  yum: name=https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
  when: ansible_distribution == "CentOS"
  become: true

- name: Install IUS (RHEL) repo.
  yum: name=https://rhel{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
  when: ansible_distribution == "Red Hat Enterprise Linux"
  become: true

- name: Import IUS Community Project GPG key
  rpm_key: key=http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY state=present
  become: true

- name: Install Python Versions
  package:
    name: "python{{ item.version }}"
    state: installed
  become: true
  with_items: "{{ python_dev_versions }}"



- name: Ensure pip activated
  command: "python{{ '.'.join(item.version)[0:3]}} -m ensurepip"
  changed_when: false
  become: true
  with_items: "{{ python_dev_versions }}"

- name: Install base dependencies (pip)
  pip:
    name: "{{ item[1] }}"
    executable: "pip{{ '.'.join(item[0].version)[0:3] }}"
  with_nested:
    - "{{ python_dev_versions }}"
    - "{{ python_dev_pip }}"
  become: yes